defaults_dir: &dir
  working_directory: ~/rrt

defaults_image: &image
  docker:
    - image: robojackets/rrt:master

defaults_deps: &install_deps
  run: sudo ./ci/ubuntu-setup.sh

version: 2
jobs:
  compile:
    <<: *dir
    <<: *image
    steps:
      - checkout
      # Ensure latest deps are installed
      - <<: *install_deps
      - run: make

  tests:
    <<: *dir
    <<: *image
    steps:
      - checkout
      # Ensure latest deps are installed
      - <<: *install_deps
      - run: make tests

  style:
    <<: *dir
    <<: *image
    steps:
      - checkout
      # Ensure latest deps are installed
      - <<: *install_deps
      - run: git fetch origin && STYLIZE_DIFFBASE=origin/master make checkstyle
      - store_artifacts:
          path: /tmp/clean.patch

workflows:
  version: 2
  build_and_test:
    jobs:
      - compile
      - tests:
          requires:
            - compile
      - style:
          requires:
            - compile
