
Import('*')

# Qt
env['QT4DIR'] = '/usr/local/Cellar'
env.Tool('qt4')
env.EnableQt4Modules(['QtCore', 'QtGui', 'QtNetwork', 'QtXml', 'QtOpenGL'])


env.Append(CPPPATH = ['#/src'])

srcs = [
	'MainWindow.cpp',
	'RRTWidget.cpp',
	'main.cpp',
	'../2dplane/2dplane.cpp'
]

env.Program('rrt-viewer', srcs)
